eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8000/eureka/
mybatis:
    config-location: classpath:mybatisConfig/mybatis-configuration.xml
    mapper-locations: classpath:mybatisConfig/mapper/*.xml
server:
    port: 9003
spring:
    application:
        name: pattern-server
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: config,stat,wall,slf4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20.0
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: 12345678
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1/trans?serverTimezone=GMT%2b8&useSSL=false&rewriteBatchedStatements=true
        username: root
        validationQuery: SELECT 1 FROM DUAL
