eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
log:
    base:
        path: /data/app/logs
    common:
        level: INFO
server:
    port: 8000
spring:
    application:
        name: spring-cloud-pay-eureka
web:
    project:
        name: spring-cloud-pay-eureka
